language: objective-c # lol
osx_image: xcode8
xcode_project: DVR.xcodeproj

script: xcodebuild -scheme "$TRAVIS_XCODE_SCHEME" -destination "$DESTINATION" test

matrix:
  include:
    - xcode_scheme: DVR-iOS
      xcode_sdk: iphonesimulator
      env:
        - DESTINATION='platform=iOS Simulator,name=iPhone 7,OS=10.0'
    - xcode_scheme: DVR-OSX
      xcode_sdk: macosx
      env:
        - DESTINATION='platform=OS X,arch=x86_64'

