language: objective-c # lol
osx_image: xcode7.3
xcode_project: DVR.xcodeproj

matrix:
  include:
    - xcode_scheme: DVR-iOS
      xcode_sdk: iphonesimulator
    - xcode_scheme: DVR-OSX
      xcode_sdk: macosx
